const { TOOLS, DOMAINS } = require('../lib/config');

/**
 * Generate README.md content for the generated configuration
 * @param {Object} config - Configuration object
 * @param {Object} result - Generation result
 * @returns {string} README content
 */
function generateReadme(config, result) {
  const tool = TOOLS[config.tool];
  const timestamp = new Date().toISOString();

  return `# Development Skills Configuration

> Generated with [SkillSet](https://github.com/patricio0312rev/skillset)

## Overview

- **Tool**: ${tool.name}
- **Location**: \`${config.folder}/\`
- **Domains**: ${config.domains.length}
- **Skills**: ${result.skillsGenerated}
- **Generated**: ${new Date().toLocaleString()}

## Usage

${getDetailedUsageInstructions(config.tool, config.folder)}

## Structure

\`\`\`
${config.folder}/
${generateStructureTree(config)}
\`\`\`

## Domains Included

${generateDomainsList(config)}

## Updating

To regenerate or update your configuration:

\`\`\`bash
npx @patricio0312rev/skillset init
\`\`\`

Or if installed globally:

\`\`\`bash
skillset init
\`\`\`

## Resources

- [SkillSet Documentation](https://github.com/patricio0312rev/skillset)
- [Skills Collection](https://github.com/patricio0312rev/skills)
- [Claude Code Documentation](https://claude.com/claude-code)
- [Agent Skills Documentation](https://agentskills.io)

## Tips

- Commit these files to version control
- Share with your team for consistent AI assistance
- Update regularly as your project evolves
- Customize skill instructions for your specific needs

---

*Generated by SkillSet v${require('../../package.json').version}*
`;
}

function getDetailedUsageInstructions(tool, folder) {
  const instructions = {
    'claude-code': `### With Claude Code

Skills in this folder are automatically loaded by Claude Code.

\`\`\`bash
# Skills are available in your Claude Code session
# Reference them in your prompts
"Use the api-endpoint-generator skill to create a REST API"
\`\`\`

### In VS Code / IDE

Skills are loaded from \`${folder}/\` automatically when you open this project in an IDE with Claude Code integration.`,

    'copilot': `### With GitHub Copilot (Agent Skills)

Skills in this folder follow GitHub's Agent Skills format and are automatically recognized by GitHub Copilot.

\`\`\`bash
# Skills are available when working in this repository
# GitHub Copilot will use them automatically for suggestions and code generation
\`\`\`

**Note**: GitHub also supports skills in \`.claude/skills/\` as a fallback location.`,

    'cursor': `### With Cursor

Skills in this folder are formatted as Project Rules for Cursor.

\`\`\`
# Use @-mentions in Cursor chat:
@.cursor/rules/api-endpoint-generator/RULE.md

# Or reference naturally in prompts:
"Using the API endpoint generator rule, create a REST API..."
\`\`\`

Cursor automatically detects and loads rules from \`.cursor/rules/\`.`,

    'other': `### With Any AI Tool

Skills in this folder use a universal format compatible with most AI coding assistants.

**Methods**:

1. **Upload Method**: Upload relevant skill files to your AI chat
2. **Reference**: Reference them in your prompts
3. **Copy-Paste**: Or copy skill content directly into context

Example:
\`\`\`
[Upload: ${folder}/api-endpoint-generator/SKILL.md]

"Following the API endpoint generator skill, help me create..."
\`\`\``
  };

  return instructions[tool] || instructions.other;
}

function generateStructureTree(config) {
  const lines = ['├── README.md'];
  const toolInfo = TOOLS[config.tool];
  const fileExtension = toolInfo.fileExtension || 'SKILL.md';

  // Collect all skills across all domains
  const allSkills = [];
  config.domains.forEach((domain) => {
    const skills = DOMAINS[domain].skills;

    // Filter skills if specific ones were selected
    let displaySkills = skills;
    if (config.skills && config.skills.length > 0) {
      displaySkills = skills.filter(skill =>
        config.skills.includes(skill) ||
        config.skills.includes(`${domain}/${skill}`)
      );
    }

    displaySkills.forEach(skill => {
      allSkills.push(skill);
    });
  });

  // Display skills directly in the target folder
  allSkills.forEach((skill, index) => {
    const isLast = index === allSkills.length - 1;
    const prefix = isLast ? '└──' : '├──';
    lines.push(`${prefix} ${skill}/`);
    lines.push(`${isLast ? ' ' : '│'}   └── ${fileExtension}`);
  });

  return lines.join('\n');
}

function generateDomainsList(config) {
  return config.domains.map(domain => {
    const domainInfo = DOMAINS[domain];

    // Filter skills if specific ones were selected
    let displaySkills = domainInfo.skills;
    if (config.skills && config.skills.length > 0) {
      displaySkills = domainInfo.skills.filter(skill =>
        config.skills.includes(skill) ||
        config.skills.includes(`${domain}/${skill}`)
      );
    }

    return `### ${domainInfo.name}

${domainInfo.description}

**Skills** (${displaySkills.length}):
${displaySkills.map(skill => `- \`${skill}\``).join('\n')}
`;
  }).join('\n');
}

module.exports = {
  generateReadme
};
